apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loginapp-certificate
spec:
  secretName: k8s-secret01
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - devopslearning.live 
